### ISSUE TITLE
If it's not `node`, it's not working.

### ISSUE THREAD

**Issue by piperswe** [SignumCollective/sgnbuild#2]
Build output from either `web` or `library`:

```
Running rollup...
Build error: Error: Error transforming C:\Users\Zeb\Documents\GitHub\signum-workshop-client\src\es6\index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
```

This has been tested with the latest commit on SignumCollective/signum-workshop-client branch rewrite. I haven't looked into this issue too much, so if it's something fundamentally wrong with how I wrote `sgnbuild`, please tell me.

**Comment by i-am-tom** [comment]
I cloned the client branch, ran `sgnbuild` with `web`, `library`, and `node` in the package.json, and all rollups worked perfectly the first time; do you have more steps for reproducing this?

**Comment by piperswe** [comment]
@i-am-tom I'm going to take a look at this in a different environment.

**Comment by piperswe** [comment]
Alright, this issue is not arising on my system anymore. Maybe it was fixed upstream?
